config/routes.rb
Rails.application.routes.draw do

  resources :owners

  resources :shipment_statuses

  get "shipments/message" => 'shipments#message', :as => :message
  
  resources :shipments do
    member do
      post 'create_shipment_status'
    end
  end

  devise_for :users, :path_names => {sign_in: "login", sign_out: "logout"} do
    get 'signup' => 'devise/registrations#new', :as => :new_user_registration
    post 'signup' => 'devise/registrations#create', :as => :user_registration
    get 'users/cancel' => 'devise/registrations#cancel', :as => :cancel_user_registration
    get 'users/edit' => 'devise/registrations#edit', :as => :edit_user_registration
    put 'users' => 'devise/registrations#update'
    delete 'users/cancel' => 'devise/registrations#destroy'  
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'users/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  get 'dash', to: 'vessels#dash', :as => :dash
  get 'non_russian', to: 'vessels#non_russian', :as => :non_russian

  resources :positions
  resources :vessels do
    collection do
      get :dash
      get :maps
      get :non_russian
      get :scan
      get :scan_gps
      post :engage
    end
  end

  get 'about', to: 'static_pages#about'
  
  

  root to: 'vessels#dash'

end

app/models/owner.rb
class Owner < ActiveRecord::Base
	#validates_presence_of :name, :rus_name

	has_many :vessels
end

app/controllers/owners_controller.rb
require 'rake'
Shepherd::Application.load_tasks

class OwnersController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  def index
    @owners = Owner.preload(:vessels).order('owners.name ASC')
    #respond_with(@owners)
  end

  def show
    # respond_with(@owner)
  end

  def new
    @owner = Owner.new
    #respond_with(@owner)
  end

  def edit
  end

  def create
    @owner = Owner.new(owner_params)
    @owner.save
    #respond_with(@owner)
  end

  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: "Owner's info was successfully updated." }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully deleted.' }
      format.json { head :no_content }
      format.js
    end
    #respond_with(@owner)
  end

  private
    def set_owner
      @owner = Owner.find(params[:id])
    end

    def owner_params
      params.require(:owner).permit(:name, :rus_name, :contact, :notes)
    end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rus_name %><br>
    <%= f.text_field :rus_name %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<% title "Owners" %>

<div class="table-responsive">
  <table class="table table-hover table-condensed" >
    <thead>
      <tr>
        <th class="small col-xs-3">Name</th>
        <th class="small col-xs-3">Vessels</th>
        <th class="small col-xs-3">Contact</th>
        <th class="small col-xs-5">Notes</th>
        <th class="small col-xs-1"></th>
      </tr>
    </thead>    
    <tbody>
      <% @owners.each do |owner| %>
        <tr data-link="row" class="rowlink">
          <td><h4><%= link_to owner.name, owner_path(owner) %></h4><small><%= owner.rus_name %></small></td>
          <td><%= owner.vessels.all.count %></td>
          <td><%= owner.contact %></td>
          <td><small><%= owner.notes %></small></td>
          <td class="rowlink-skip hidden-print"><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/owners/new.html.erb
<h1>New owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @owner.name %>
</p>

<p>
  <strong>Rus name:</strong>
  <%= @owner.rus_name %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @owner.contact %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @owner.notes %>
</p>

<p>
  <strong>Vessels:</strong><br />
  <% @owner.vessels.each do |v| %>
  - <%= link_to v.vsl_name, vessel_path(v) %> (<%= v.vsl_type%>)<br />
  <% end %>
</p>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>