config/routes.rb
Rails.application.routes.draw do

  resources :owners

  resources :shipment_statuses

  get "shipments/message" => 'shipments#message', :as => :message
  
  resources :shipments do
    member do
      post 'create_shipment_status'
    end
  end

  devise_for :users, :path_names => {sign_in: "login", sign_out: "logout"} do
    get 'signup' => 'devise/registrations#new', :as => :new_user_registration
    post 'signup' => 'devise/registrations#create', :as => :user_registration
    get 'users/cancel' => 'devise/registrations#cancel', :as => :cancel_user_registration
    get 'users/edit' => 'devise/registrations#edit', :as => :edit_user_registration
    put 'users' => 'devise/registrations#update'
    delete 'users/cancel' => 'devise/registrations#destroy'  
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'users/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  get 'dash', to: 'vessels#dash', :as => :dash
  get 'non_russian', to: 'vessels#non_russian', :as => :non_russian

  resources :positions
  resources :vessels do
    collection do
      get :dash
      get :maps
      get :non_russian
      get :scan
      get :scan_gps
      post :engage
    end
  end

  get 'about', to: 'static_pages#about'
  
  

  root to: 'vessels#dash'

end

app/models/owner.rb
class Owner < ActiveRecord::Base
	#validates_presence_of :name, :rus_name

	has_many :vessels
end

app/models/vessel.rb
class Vessel < ActiveRecord::Base
	validates_presence_of :vsl_name, :vsl_type#, :vsl_flag, :blt_year

	# validates_uniqueness_of :imo
	# validates :imo, :imo_format => true

	has_many :positions
	has_many :shipments, :dependent => :destroy

	belongs_to :owner
	#select('vessels.*, COUNT(shipments.id) AS shipments_count')
	#scope :russian_vessels, -> { where("vsl_flag = ? or vsl_flag = ?", "Russia", "")}
	# 	scope :free_vessels, -> { where(never_engaged.ast.cores.last.wheres.last.or(done_vessels.ast.cores.last.wheres.inject{|ws, w| (ws &&= ws.and(w)) || w}))}
	scope :never_engaged, -> { where.not(id: Shipment.select(:vessel_id)) }
	scope :engaged_vessels, -> { includes(:positions).joins(:shipments => [:shipment_statuses]).where('shipment_statuses.created_at = (SELECT MAX(shipment_statuses.created_at) FROM shipment_statuses WHERE shipment_statuses.shipment_id = shipments.id)')}
	scope :free_vessels, -> { all }
	scope :active_vessels, -> { engaged_vessels.where.not("status = ?","Completed")}
	scope :done_vessels, -> { engaged_vessels.where("status = ?","Completed")}
end

app/controllers/vessels_controller.rb
require 'rake'
Shepherd::Application.load_tasks

class VesselsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show, :dash, :non_russian]
  before_action :set_vessel, only: [:show, :edit, :update, :destroy]


  def index
    #@all_vessels = Vessel.preload(:positions).order('vessels.vsl_name ASC').references(:positions)
    #@russian_vessels = Vessel.russian_vessels.preload(:positions).order('vessels.vsl_name ASC')
    @free_vessels = Vessel.free_vessels.order('vessels.vsl_type ASC')
    @free_russian_vessels = Vessel.free_vessels.where('vsl_flag = ?', "Russia").order('vessels.vsl_type ASC')

    respond_to do |format|
      format.pdf do
            render :pdf => "Example PDF file",
                   :template => 'vessels/all.pdf.erb',
                   :print_media_type => true,
                   :page_size => "A4"
      end
      format.html #{ render :index }
    end

  end

  def non_russian
    #@all_vessels = Vessel.preload(:positions).order('vessels.vsl_name ASC').references(:positions)
    #@russian_vessels = Vessel.russian_vessels.preload(:positions).order('vessels.vsl_name ASC')
    @non_russian_vessels = Vessel.free_vessels.where('vsl_flag != ?', "Russia").order('vessels.vsl_type ASC')

    respond_to do |format|
      format.pdf do
            render :pdf => "Example PDF file",
                   :template => 'vessels/non_russian.pdf.erb',
                   :print_media_type => true,
                   :page_size => "A4"
      end
      format.html { render :non_russian }
    end

  end

  def maps
    @active_vessels = Vessel.active_vessels.order('vessels.vsl_name ASC')

    respond_to do |format|
      format.pdf do
            render :pdf => 'Maps of currently engaged vessels',
                   :template => 'vessels/active_maps.pdf.erb',
                   :print_media_type => true,
                   :page_size => "B6",
                   :orientation => 'Landscape',
                   :save_to_file => Rails.root.join("pdf", "active_maps.pdf"),
                   :save_only    => true,
                   :margin => {:top => 5,
                           :bottom  => 5,
                           :left  => 5,
                           :right => 5},
                   :show_as_html => params[:debug].present?
            redirect_to :dash
      end
      format.html { render :dash }
    end

  end

  def dash    
    @active_vessels = Vessel.active_vessels.order('vessels.vsl_name ASC')

    respond_to do |format|
      format.pdf do
            render :pdf => "Current dashboard",
                   :template => 'vessels/active.pdf.erb',
                   :print_media_type => true,
                   :page_size => "A4"
      end
      format.html { render :dash }
    end

  end

  def show
    respond_to do |format|
      format.pdf do
            render :pdf => "Example PDF file",
                   :template => 'vessels/single.pdf.erb',
                   :print_media_type => true,
                   :page_size => "A4",
                   :orientation => 'Portrait',
                   :margin => {:top => 5,
                           :bottom  => 5,
                           :left  => 5,
                           :right => 5},
                   :show_as_html => params[:debug].present?
      end
      format.html { render :show }
    end
  end

  def new
    @vessel = Vessel.new
  end

  def edit
  end

  def create
    @vessel = Vessel.new(vessel_params)

    respond_to do |format|
      if @vessel.save
        format.html { redirect_to @vessel, notice: 'Vessel card was successfully created.' }
        format.json { render :show, status: :created, location: @vessel }
        format.js { redirect_to @vessel, notice: 'Vessel card was successfully created.' }
      else
        format.html #{ render :new }
        format.json { render json: @vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @vessel.update(vessel_params)
        format.html { redirect_to @vessel, notice: "Vessel's info was successfully updated." }
        format.json { render :show, status: :created, location: @vessel }
      else
        format.html { render :edit }
        format.json { render json: @vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @vessel.destroy
    respond_to do |format|
      format.html { redirect_to vessels_url, notice: 'Vessel was successfully deleted.' }
      format.js
      format.json { head :no_content }
    end
  end

  # def scan
  #     Rake::Task['crawl:new'].invoke
  #     Rake::Task['crawl:new'].reenable
      
  #     respond_to do |format|
  #       format.html { redirect_to vessels_url, success: 'Vessels have been scanned!' }
  #       format.json { head :no_content }
  #     end
  # end

  def scan
      Rake::Task['crawl:new'].invoke(params[:vessel_imos])
      Rake::Task['crawl:new'].reenable

      respond_to do |format|
        format.html { redirect_to dash_path, success: 'Vessel information has been updated!' }
        format.json { head :no_content }
        format.js
      end
  end

  def scan_gps
      Rake::Task['crawl:gps'].reenable
      Rake::Task['crawl:gps'].invoke(params[:vessel_imos])

      respond_to do |format|
        format.html { redirect_to :dash, success: 'Vessel GPS has been updated!' }
        format.json { head :no_content} #{vessel_path(params[:id])}}
        format.js
      end
  end

  def engage
    vessels = Vessel.where(:id => params[:vessel_ids])
    vessels.each do |v|
      s = v.shipments.build(:title => "Change this name")
      v.save!
      s.shipment_statuses.build(:title => "Change this name", :status => "Initialized", :shipment_id => s.id)
      s.save!
    end
    redirect_to :dash
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vessel
      @vessel = Vessel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vessel_params
      params.require(:vessel).permit(:vsl_name, :vsl_type, :blt_year, :vsl_flag, :imo, :mmsi)
    end
end

app/helpers/vessels_helper.rb
module VesselsHelper
end

app/views/vessels/_active_maps.html.erb
<% @active_vessels.each do |vessel| %>
  <% unless @active_vessels.empty? %>
      <div class="panel panel-info page-break">
        <div class="panel-heading">
          <h1 class="panel-title" >
              <%= vessel.vsl_name %> 
              <% if vessel.positions.last.nav_status =~ /Way|Underway/ %>
                <span class="label label-success"><%= vessel.positions.last.nav_status %></span>
              <% elsif vessel.positions.last.nav_status =~ /Unknown/%>
                <span class="label label-default"><%= vessel.positions.last.nav_status %></span>
              <% else %>
                <span class="label label-warning"><%= vessel.positions.last.nav_status %></span>
              <% end %>
          </h1>
        </div>
        <% unless vessel.positions.empty? || vessel.positions.last.long.blank? || vessel.positions.last.lat.blank? %>
          <% icon = URI.encode("icon:http://chart.apis.google.com/chart?chst=d_map_pin_icon_withshadow&chld=sail|color:black|label:#{vessel.vsl_name}|", "&, |")%>

          <% boom = "http://maps.googleapis.com/maps/api/staticmap?zoom=7&size=600x480&scale:2&format=png32&maptype=roadmap&markers=#{icon}#{vessel.positions.last.lat},#{vessel.positions.last.long}" %>

        <div class="panel-body last-map-print" style="background: url('<%= boom %>') center no-repeat" >
        </div>
        <% end %>
      </div>
  <% end %>
<% end %>

app/views/vessels/_all_vessels.html.erb
<% title "All vessels" %>
	<div class="table-responsive">
      <table class="table table-hover table-condensed" >
          <thead>
            <tr>
              <th class="small hidden-print"><input type="checkbox"></th>
              <th class="small hidden-print">
              <th class="small text-left col-xs-2">Vessel</th>
              <th class="small">Type</th>
              <th class="small col-xs-1">Built</th>
              <% if !user_signed_in? %>
                <th class="small">IMO (MMSI)</th>
              <% end %>
              <% if user_signed_in? %>
                <th class="small col-xs-1">Owner</th>
              <% end %>
              <th class="small">Last&nbsp;Upd</th>
              <th class="small hidden-print">Built</th>
              <th class="small">Destination</th>
              <th class="small col-xs-2">ETA</th>
              <th colspan="1" class="small hidden-print"></th>
            </tr>
          </thead>
          <tbody>
            <% unless @free_vessels.nil? %>
              <% @free_vessels.each do |vessel| %>
                <tr data-link="row" class="small rowlink">
                  <td class="rowlink-skip hidden-print">
                    <% if vessel.created_at > Date.today-3 %>
                      <span class="label label-info">new</span>
                    <% end %>
                  </td>
                  <td class="text-left col-xs-2"><%= vessel.vsl_name %>
                    <% if user_signed_in? %>
                    (<%= vessel.imo %>)
                    <% end %>
                  </td>
                  <td><%= vessel.vsl_type %></td>
                  <% if !user_signed_in? %>
                     <td class="rowlink-skip"><%= vessel.imo %> (<%= vessel.mmsi %>)</td>
                  <% end %>

                  <td class="col-xs-1"><%= vessel.blt_year.to_formatted_s(:just_year) unless vessel.blt_year.nil? %></td>

                  <td class="col-xs-2">
                    <% if user_signed_in? %>
                      <% unless vessel.owner.nil? %>
                        <% if !vessel.owner.name.nil? %>
                          <small><%= vessel.owner.name %><small>
                        <% elsif !vessel.owner.notes.nil? %>
                          <small><%= vessel.owner.notes %><br /></small>
                        <% else %>
                          <kbd><samp><%= "UNKNOWN" %></samp></kbd><br />
                        <% end %>
                      <% end %>
                    <% end %>
                  </td>

                  <td><%= vessel.positions.last.last_upt.to_formatted_s(:day_month) unless vessel.positions.nil? || vessel.positions.last.nil? || vessel.positions.last.last_upt.nil?%></td>
                  <td class="hidden-print"><%= vessel.blt_year.to_formatted_s(:just_year) unless vessel.blt_year.nil? %></td>
                  <td>
                    <% if !vessel.positions.last.nil? then %>
                      <% if !vessel.positions.last.prev_dest.blank? then %>
                        <%= vessel.positions.last.prev_dest %> 
                      <% else %>
                        <kbd><samp><%= "UNKNOWN" %></samp></kbd>
                      <% end %>
                      > 
                      <% if !vessel.positions.last.dest.blank? then %>
                        <%= vessel.positions.last.dest %> 
                      <% else %>
                        <kbd><samp><%= "UNKNOWN" %></samp></kbd>
                      <% end %>
                    <% end %>
                  </td>
                  <td>
                    <% if !vessel.positions.last.nil? then %>
                      <% if !vessel.positions.last.eta.blank? then %>
                        <%= vessel.positions.last.eta.to_formatted_s(:day_month_year) %>
                      <% else %>
                        <kbd><samp><%= "UNKNOWN" %></samp></kbd>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
      </table>
    </div>

app/views/vessels/dash.html.erb
<% title "Dashboard | #{@active_vessels.count}" %>
<%= form_tag scan_vessels_path, :method => :get do %>
    <% if user_signed_in? %>
        <div class="hidden-print">
            <span class="badge"><%= @active_vessels.count %></span>
            <%= submit_tag 'Update', :class => "btn btn-default btn-xs hidden-print" %> 
            <%= link_to 'PDF', dash_path(:format => :pdf), :class => "btn btn-xs btn-default hidden-print" %>
            <%= link_to 'Save maps', maps_vessels_path(:format => :pdf), :class => "btn btn-xs btn-default hidden-print" %>
        </div>
        <br/>
    <% end %>
    <div class="table-responsive">  
        <% if !@active_vessels.blank? %>
            <% @active_vessels.each do |vessel| %>
                <div class="panel-group" id="#accordian">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h1 class="panel-title" >
                                <div class="row">
                                    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-5">
                                        <%= hidden_field_tag 'vessel_imos[]', vessel.imo %>
                                        <%= link_to vessel.vsl_name, vessel_path(vessel) %>
                                    </div>
                                    <div class="col-xs-6 col-sm-5 col-md-4 col-lg-4">
                                        <% if !vessel.positions.last.nil? %>
                                            <% if vessel.positions.last.nav_status =~ /Way|Underway/ %>
                                                <span class="label label-success"><%= vessel.positions.last.nav_status %></span>
                                            <% elsif vessel.positions.last.nav_status =~ /Unknown/%>
                                                <span class="label label-default"><%= vessel.positions.last.nav_status %></span>
                                            <% else %>
                                                <span class="label label-warning"><%= vessel.positions.last.nav_status %></span>
                                            <% end %>

                                            <span class="hidden-xs">
                                                <small>(LAST UPDATE: <strong><%= vessel.positions.last.updated_at.strftime("%d-%b %H:%M") %>)</strong>
                                                </small>
                                            </span>
                                        <% end %>
                                    </div>
                                    <% if user_signed_in? %>
                                        <div class="col-xs-6 col-sm-2 col-md-2 col-lg-2 pull-right hidden-print">
                                            <button type="button" class="btn btn-xs btn-default">Wha?</button>
                                            <button type="button" class="btn btn-xs btn-info">No-o</button>
                                        </div>
                                    <% end %>
                                </div>
                            </h1>
                        </div>

                        <div class="panel-body">
                            <div class="row">
                                <div class="col-xs-12 col-sm-5 col-lg-5">
                                    <div class="row">
                                        <div class="col-xs-7 col-sm-8 col-lg-9">
                                            <small>Direction</small>
                                        </div>
                                        <div class="col-xs-5 col-sm-4 col-lg-3">
                                            <small>ETA</small>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <hr>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-7 col-sm-8 col-lg-9">
                                            <% if !vessel.positions.last.nil? then %>
                                                <h4>
                                                    <% if !vessel.positions.last.prev_dest.blank? then %>
                                                        <%= vessel.positions.last.prev_dest %>
                                                    <% else %>
                                                        <kbd><samp><%= "UNKNOWN" %></samp></kbd>
                                                    <% end %>
                                                        <span class="glyphicon glyphicon-arrow-right"></span> 
                                                    <% if !vessel.positions.last.dest.blank? then %>
                                                        <%= vessel.positions.last.dest %>
                                                    <% else %>
                                                        <kbd><samp><%= "UNKNOWN" %></samp></kbd>
                                                    <% end %>
                                                </h4>
                                            <% end %>
                                        </div>
                                        <div class="col-xs-5 col-sm-4 col-lg-3">
                                            <h4>
                                                <% if !vessel.positions.last.nil? then %>
                                                    <% if !vessel.positions.last.eta.blank? then %>
                                                        <%= vessel.positions.last.eta.to_formatted_s(:day_month)  unless vessel.positions.nil? || vessel.positions.last.nil? || vessel.positions.last.eta.nil?%>&nbsp;
                                                    <% else %>
                                                        <kbd><samp><%= "UNKNOWN" %>&nbsp;</samp></kbd>
                                                    <% end %>
                                                <% end %>
                                            </h4>
                                        </div>
                                        <br />
                                    </div>
                                    
                                    <% if user_signed_in? %>
                                        <div class="row hidden-print">
                                            <div class="hidden-print col-xs-12">
                                                <% if !vessel.positions.last.nil? && !vessel.positions.last.now_near.blank? %>
                                                    The vessel is currently near <strong><%= vessel.positions.last.now_near %></strong>
                                                <% else %>
                                                    <% if !vessel.positions.last.nil? %>
                                                        <small>
                                                            <strong>Lat:</strong>
                                                            <% if !vessel.positions.last.lat.nil? %>
                                                                <samp><%= vessel.positions.last.lat %></samp>, 
                                                            <% else %>
                                                                <kbd><samp><%= "UNKNOWN" %></samp></kbd>, 
                                                            <% end %>
                                                            <strong>Long:</strong>
                                                            <% if !vessel.positions.last.long.nil? %>
                                                                <samp><%= vessel.positions.last.long %></samp>
                                                            <% else %>
                                                                <kbd><samp><%= "UNKNOWN" %></samp></kbd>
                                                            <% end %>
                                                        </small>
                                                        
                                                    <% end %>
                                                <% end %>
                                            </div>
                                        </div>
                                    <% end %>
                                    <br />
                                    <% if user_signed_in? %>
                                        <%= render partial: 'vessels/vessel_data', locals: {vessel: vessel} %>
                                    <% end %>
                                    
                                    <br / class="hidden-xs">
                                    <% if user_signed_in? %>
                                        <div class="row hidden-xs">
                                            <p class="hidden-print col-xs-12">
                                                <%= link_to 'Edit', edit_vessel_path(vessel) %> |
                                                <%= link_to 'Add new vessel', new_vessel_path %>
                                            </p>
                                        </div>
                                    <% end %>
                                </div>
                                <div class="col-xs-12 col-sm-7 col-lg-7">
                                  <% unless vessel.positions.empty? || vessel.positions.last.long.blank? || vessel.positions.last.lat.blank? %>
                                    <% icon = URI.encode("icon:http://chart.apis.google.com/chart?chst=d_map_pin_icon_withshadow&chld=sail|color:black|label:|", "&, |")%>

                                    <% boom = "http://maps.googleapis.com/maps/api/staticmap?zoom=7&size=640x300&scale:2&maptype=roadmap&markers=#{icon}#{vessel.positions.last.lat},#{vessel.positions.last.long}" %>

                                    <div style="background: url('<%= boom %>') center no-repeat" class="last-map">
                                      <div>
                                        <label class="map_sign hidden-print hidden-xs">
                                          <%= vessel.vsl_name %> (<%= vessel.imo %>)
                                        </label>
                                      </div>
                                    </div>
                                    <br / class="hidden-print">
                                  <% end %>
                                  <p class="hidden-print hidden-xs">
                                    <% unless vessel.imo.nil? %>
                                        See the <%= link_to "position", 'http://www.marinetraffic.com/ais/embed/zoom:7/maptype:2/notation:true/shownames:true/mmsi:'+ vessel.mmsi + '/' %> or <%= link_to "general info", 'http://www.marinetraffic.com/en/ais/details/ships/'+ vessel.imo + '/' %> on the MarineTraffic website
                                      <% end %>
                                  </p>
                                  <p class="hidden-print hidden-xs">
                                    <% unless vessel.imo.nil? %>
                                        See the <%= link_to "position", 'http://www.vesselfinder.com/en-us/?mmsi='+ vessel.mmsi %> on the VesselFinder website
                                    <% end %>
                                  </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        <% else %>
            <h3>
              There is currently no actively engaged vessels
            </h3>
        <% end %>
    </div>
<% end %>

app/views/vessels/index.html.erb
<% title "Vessels | #{@free_russian_vessels.count}" %>
<%= form_tag engage_vessels_path, :method => :post do %>
  <% if user_signed_in? %>
    <div class="hidden-print">
      <span class="badge"><%= @free_russian_vessels.count %></span>
      <%= submit_tag 'Engage', :class => "btn btn-default btn-xs hidden-print" %>
      <%= link_to 'New vessel', new_vessel_path, :class => "btn btn-xs btn-default hidden-print" %>&nbsp;&nbsp;&nbsp;&nbsp;
      <%= link_to 'Scan', {:controller => :vessels, :action => :scan}, :class => "btn btn-default btn-xs hidden-print" %>
      <%= link_to 'PDF', vessels_path(:format => :pdf), :class => "btn btn-xs btn-default hidden-print" %>
    </div>
    <br />
  <% end %>

<div class="table-responsive">
  <table class="table table-hover table-condensed" > 
      <thead>
        <tr>
          <th class="small hidden-print"><input type="checkbox"></th>
          <th class="small col-xs-2">Vessel</th>
          <th class="small col-xs-1">Type</th>
          <% if !user_signed_in? %>
            <th class="small col-xs-2">IMO (MMSI)</th>
          <% end %>
          <% if user_signed_in? %>
            <th class="small col-xs-1">Owner</th>
          <% end %>
          <th class="small col-xs-1">Last&nbsp;Upd</th>
          <th class="small col-xs-1 hidden-print">Built</th>
          <th class="small col-xs-2">Destination</th>
          <th class="small col-xs-1">ETA</th>
          <% if !user_signed_in? %>
            <th class="small col-xs-1 hidden-print"></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% unless @free_russian_vessels.nil? %>
          <% @free_russian_vessels.each do |vessel| %>
            <tr data-link="row" class="rowlink">
              <td class="rowlink-skip hidden-print"> 
                <%= check_box_tag('vessel_ids[]', vessel.id) %>
              </td>
              <td class="text-left col-xs-2">
                <% if vessel.created_at > Date.today-3 %>
                  <span class="label label-info">new</span>
                <% end %>
                <%= link_to vessel.vsl_name, vessel_path(vessel) %>
                <% if user_signed_in? %>
                  (<%= vessel.imo %>)
                <% end %>
              </td>
              <td class="col-xs-"><%= vessel.vsl_type %></td>
              <% if !user_signed_in? %>
                 <td class="rowlink-skip"><%= vessel.imo %> (<%= vessel.mmsi %>)</td>
              <% end %>

              <td class="col-xs-2">
                <% if user_signed_in? %>
                  <% unless vessel.owner.nil? %>
                    <% if !vessel.owner.name.nil? %>
                      <small><%= vessel.owner.name %><small>
                    <% elsif !vessel.owner.notes.nil? %>
                      <small><%= vessel.owner.notes %><br /></small>
                    <% else %>
                      <kbd><samp><%= "UNKNOWN" %></samp></kbd><br />
                    <% end %>
                  <% end %>
                <% end %>
              </td>
              
              <td class="col-xs-1"><%= vessel.positions.last.last_upt.to_formatted_s(:day_month) unless vessel.positions.nil? || vessel.positions.last.nil? || vessel.positions.last.last_upt.nil?%></td>
              <td class="hidden-print col-xs-1"><%= vessel.blt_year.to_formatted_s(:just_year) unless vessel.blt_year.nil? %></td>
              <td class="col-xs-3">
                <% if !vessel.positions.last.nil? then %>
                  <% if !vessel.positions.last.prev_dest.blank? then %>
                    <% if vessel.positions.last.prev_dest.length > 20 then %>
                      <%= vessel.positions.last.prev_dest[0..20] %> 
                    <% else %>
                      <%= vessel.positions.last.prev_dest %> 
                    <% end %>
                  <% else %>
                    <kbd><samp><%= "UNKNOWN" %></samp></kbd>
                  <% end %>
                  <span class="glyphicon glyphicon-arrow-right"></span> 
                  <% if !vessel.positions.last.dest.blank? then %>
                    <% if vessel.positions.last.dest.length > 20 then %>
                      <%= vessel.positions.last.dest[0..20] %> 
                    <% else %>
                      <%= vessel.positions.last.dest %> 
                    <% end %>
                  <% else %>
                    <kbd><samp><%= "UNKNOWN" %></samp></kbd>
                  <% end %>
                <% end %>
              </td>
              <td class="col-xs-1">
                <% if !vessel.positions.last.nil? then %>
                  <% if !vessel.positions.last.eta.blank? then %>
                    <%= vessel.positions.last.eta.to_formatted_s(:day_month_year) %>
                  <% else %>
                    <kbd><samp><%= "UNKNOWN" %></samp></kbd>
                  <% end %>
                <% end %>
              </td>
              <% if user_signed_in? %>
                <td class="rowlink-skip hidden-print"><%= link_to '<i class="glyphicon glyphicon-remove"></i>'.html_safe, vessel, :class => 'delete', method: :delete, remote: true %>
                </td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
  </table>
</div>
<% end %>

app/views/vessels/new.html.erb
<% title "New Vessel" %>
<h1><% yield(:title)%></h1>

<%= render 'imoform' %>