config/routes.rb
Rails.application.routes.draw do

  resources :owners

  resources :shipment_statuses

  get "shipments/message" => 'shipments#message', :as => :message
  
  resources :shipments do
    member do
      post 'create_shipment_status'
    end
  end

  devise_for :users, :path_names => {sign_in: "login", sign_out: "logout"} do
    get 'signup' => 'devise/registrations#new', :as => :new_user_registration
    post 'signup' => 'devise/registrations#create', :as => :user_registration
    get 'users/cancel' => 'devise/registrations#cancel', :as => :cancel_user_registration
    get 'users/edit' => 'devise/registrations#edit', :as => :edit_user_registration
    put 'users' => 'devise/registrations#update'
    delete 'users/cancel' => 'devise/registrations#destroy'  
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'users/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  get 'dash', to: 'vessels#dash', :as => :dash
  get 'non_russian', to: 'vessels#non_russian', :as => :non_russian

  resources :positions
  resources :vessels do
    collection do
      get :dash
      get :maps
      get :non_russian
      get :scan
      get :scan_gps
      post :engage
    end
  end

  get 'about', to: 'static_pages#about'
  
  

  root to: 'vessels#dash'

end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
	validates_presence_of :title, :vessel_id
	
	belongs_to :vessel
	has_many :shipment_statuses, :dependent => :destroy
	accepts_nested_attributes_for :shipment_statuses

	scope :engaged, -> { includes(:shipment_statuses).where('shipment_statuses.created_at = (SELECT MAX(shipment_statuses.created_at) FROM shipment_statuses WHERE shipment_statuses.shipment_id = shipments.id)')}
	scope :active, -> { engaged.where.not("shipment_statuses.status = ?", "Completed").references(:shipment_statuses)}
	scope :done, -> { engaged.where("shipment_statuses.status = ?", "Completed").references(:shipment_statuses)}
end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :set_shipment, only: [:show, :edit, :update, :destroy]

  # GET /shipments
  # GET /shipments.json
  def index
    @active_shipments = Shipment.includes(:shipment_statuses).active
    @completed_shipments = Shipment.includes(:shipment_statuses).done
  end

  # GET /shipments/1
  # GET /shipments/1.json
  def show
    respond_to do |format|
      format.html
      format.js {}
    end
  end

  def new
    @shipment = Shipment.new
  end

  def edit
  end

  def message
    #@selected = Shipment.find(params[:shipment])
    respond_to do |format|
      format.html
      format.js {}
    end
  end

 
  def create
    @shipment = Shipment.new(shipment_params)
    @shipment.save!
    @shipment.shipment_statuses.build(:title => "Change this name", :status => "Initialized", :shipment_id => @shipment.id)
    @shipment.save!
    respond_to do |format|
      if @shipment.save
        format.html { redirect_to @shipment, notice: 'Shipment was successfully created.' }
        format.json { render :show, status: :created, location: @shipment }
      else
        format.html { render :new }
        format.json { render json: @shipment.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_shipment_status
    @shipment = Shipment.find(params[:id]) 
    @shipment_status = @shipment.shipment_statuses.build(:shipment_id => params[:id], :status => params[:shipment_status][:status], :description => params[:shipment_status][:description], :start_time => params[:shipment_status][:start_time], :comp_time => params[:shipment_status][:comp_time])
    @shipment_status.save!
    if @shipment_status.save
      @shipment_status = ShipmentStatus.new
    else
      render html: @shipment.errors, status: :unprocessable_entity
    end
    redirect_to :action => :show
  end

  # PATCH/PUT /shipments/1
  # PATCH/PUT /shipments/1.json
  def update
    respond_to do |format|
      if @shipment.update(shipment_params)
        format.html { redirect_to @shipment, notice: 'Shipment was successfully updated.' }
        format.json { render :show, status: :ok, location: @shipment }
      else
        format.html { render :edit }
        format.json { render json: @shipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shipments/1
  # DELETE /shipments/1.json
  def destroy
    @shipment.destroy
    respond_to do |format|
      format.html { redirect_to shipments_url, notice: 'Shipment was successfully deleted.' }
      format.js
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shipment
      @shipment = Shipment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shipment_params
      params.require(:shipment).permit(:status, :vessel_id)
    end
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/views/shipments/_form.html.erb
<%= form_for(@shipment, :validate => true, :class => "form-horizontal", :role => "form") do |f| %>
<div class="form-group row">
  <div class="col-sm-1">
    <label for="inputTitle" class="control-label vmiddle">Title</label>
  </div>
  <div class="field col-sm-5 row">
    <%= f.text_field :title, :class => "form-control", :id => "inputTitle", :placeholder => "Please type a short title for this shipment" %>
  </div>
</div>
<div class="form-group row">
  <div class="col-sm-1">
    <label for="inputVessel" class="control-label vmiddle">Vessel</label>
  </div>
  <div class="field col-sm-5 row">
    <%= f.text_field :vessel_id, :class => "form-control", :id => "inputVessel", :placeholder => "Choose the vessel"  %>
  </div>
</div>
<div class="actions form-group row">
  <div class="field col-sm-6">
    <%= f.submit "Update", :class => "btn btn-lg btn-primary" %>&nbsp;&nbsp;&nbsp;
    <%= link_to 'Back', shipments_path, :class => "vbottom" %>
  </div>
</div>
<% end %>

app/views/shipments/destroy.js.erb
$('a.delete').on('click', function() {
	if(confirm("Are you sure?")){
		$('#shipment_<%= @shipment.id %>').remove();
		$(this).closest('tr').delay().fadeOut();
	}else{
		return false;
	}
});

app/views/shipments/edit.html.erb
<%= render 'form' %>

app/views/shipments/index.html.erb
<% title "Shipments" %>
<h3> Active shipments <span class="badge"><%= @active_shipments.count %></span></h3>
<% unless @active_shipments.empty? %>
  <div class="table-responsive">
    <table class="table table-hover table-condensed" >
      <thead>
        <tr>
          <th class="small"><input type="checkbox"></th>
          <th class="small"></th>
          <th class="small hidden-xs">Status</th>
          <th class="small hidden-xs"></th>
        </tr>
      </thead>

      <tbody>
        <% @active_shipments.each do |shipment| %>
          <tr data-link="row" class="rowlink">
            <td class="rowlink-skip hidden-print">
              <input type="checkbox">
            </td>
            <td class="col-xs-12 hidden-sm hidden-md hidden-lg pull-left"><small>
              <strong><%= link_to "#{Vessel.find_by_id(shipment.vessel_id).vsl_name}", shipment_path(shipment) %></strong> | <%= shipment.shipment_statuses.last.status unless shipment.shipment_statuses.empty? %>
            (<%= shipment.shipment_statuses.last.created_at.to_formatted_s(:d_m) %>)</small>
            </td>
            
            <td class="hidden-xs col-sm-9 col-md-9 col-lg-10">
              <strong><%= link_to "#{Vessel.find_by_id(shipment.vessel_id).vsl_name}", shipment_path(shipment) %></strong> | <%= shipment.shipment_statuses.last.description unless shipment.shipment_statuses.last.description.nil? %>
            </td>
            <td class="hidden-xs">
              <%= shipment.shipment_statuses.last.status unless shipment.shipment_statuses.empty? %>
              (<%= shipment.shipment_statuses.last.created_at.to_formatted_s(:d_m) %>)
            </td>
            <td class="rowlink-skip hidden-xs"><%= link_to '<i class="glyphicon glyphicon-remove"></i>'.html_safe, shipment, class: "delete", method: :delete, remote: true %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
<p>
  There are no active shipments at this time.
</p>
<% end %>
<h3>Archive <span class="badge"><%= @completed_shipments.count %></span></h3>
<% unless @completed_shipments.empty? %>
  <div class="table-responsive">
    <table class="table table-hover table-condensed" >
      <thead>
        <tr>
          <th class="small"><input type="checkbox"></th>
          <th class="small"></th>
          <th class="small hidden-xs">Period</th>
        </tr>
      </thead>

      <tbody>
        <% @completed_shipments.each do |shipment| %>
          <tr data-link="row" class="rowlink">
            <td class="rowlink-skip hidden-print">
              <input type="checkbox">
            </td>
            <td class="col-xs-12 hidden-lg hidden-md hidden-sm pull-left"><small><strong><%= link_to "#{Vessel.find_by_id(shipment.vessel_id).vsl_name}", shipment_path(shipment) %></strong> (<%= shipment.shipment_statuses.last.created_at.to_formatted_s(:d_m) unless shipment.shipment_statuses.empty? %>&mdash;<%= shipment.shipment_statuses.first.created_at.to_formatted_s(:d_m) unless shipment.shipment_statuses.empty? %>)</small>
            </td>
            <td class="hidden-xs col-sm-9 col-md-9 col-lg-10"><strong><%= link_to "#{Vessel.find_by_id(shipment.vessel_id).vsl_name}", shipment_path(shipment) %></strong>
            </td>
            <td class="hidden-xs">(<%= shipment.shipment_statuses.last.created_at.to_formatted_s(:d_m) unless shipment.shipment_statuses.empty? %>&mdash;<%= shipment.shipment_statuses.first.created_at.to_formatted_s(:d_m) unless shipment.shipment_statuses.empty? %>)</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
<p>
  There are no archive shipments at this time.
</p>
<% end %>
<br>

<%= link_to 'New Shipment', new_shipment_path %>

app/views/shipments/message.js.erb
$(document).ready(function () {
  $("#messageModal").on('shown.bs.modal', function(e) {
  var button = $(e.relatedTarget) // Button that triggered the modal
  var recipient = button.data('recipient') // Extract info from data-* attributes
  var subject = button.data('subject')
  // var message = button.data('message')
  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
  var modal = $(this)
  modal.find('.modal-title').text('New message to ' + recipient)
  modal.find('#recipient-name').val(recipient)
  modal.find('#subject-text').val('MV "' + subject +'"')
  // modal.find('#message-text').val(message)
  });
  $("#messageModal").on("click", ".send", function(e) {
      bootbox.alert("Message sent!", function() {
      console.log("Alert Callback");
    });
  });
});
// $(document).ready(function () {
//   $("#messageModal").on("click", ".send", function(e) {
//       bootbox.alert("Message sent!", function() {
//       console.log("Alert Callback");
//     });
//   });
// });

app/views/shipments/new.html.erb
<h2>New shipment</h2>
<br />
<%= render 'form' %>

app/views/shipments/show.html.erb
<% title "Shipment" %>
<!-- Modal -->
<div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="messageModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
			  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			  <h4 class="modal-title" id="messageModalLabel">Sending status to clients</h4>
			</div><!-- modal-header -->
			<div class="modal-body">
			  <form>
			    <div class="form-group">
			      <label for="recipient-name" class="control-label">Recipients:</label>
			      <input type="text" class="form-control" id="recipient-name">
			    </div>
			    <div class="form-group">
			      <label for="subject-text" class="control-label">Subject:</label>
			      <input type="text" class="form-control" id="subject-text">
			    </div>
			    <div class="form-group">
			      <label for="message-text" class="control-label">Message:</label>
			      <textarea class="form-control" id="message-text"></textarea>
			    </div>
			  </form>
			</div><!-- modal-body -->
			<div class="modal-footer">
			  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			  <button type="button" class="btn btn-primary send">Send message</button>
			</div>
		</div><!-- modal-content -->
	</div><!-- modal-dialog -->
</div><!-- modal -->
<H2>
  <strong>M/V &ldquo;<%= @shipment.vessel.vsl_name %>&rdquo;</strong>
</H2>
<div>
	<hr class="hidden-xs">
</div>
<% @shipment.shipment_statuses.order('start_time ASC').each_with_index do |s, index| %>
	<div class="row">
		<h5>
			<div class="hidden-xs col-sm-3 col-md-2 col-lg-2 pull-left">
				<strong>
					<% if !s.start_time.nil?%>
						<%= s.start_time.to_formatted_s(:d_m_y)%>
					<% end %>
				</strong>
				<% if !s.start_time.nil? %>
					(<%= s.start_time.to_formatted_s(:h_m)%>)<br />
				<% else %>
					( &#63; )
				<% end %>
				<strong>
					<% if !s.comp_time.nil?%>
						<%= s.comp_time.to_formatted_s(:d_m_y)%>
					<% end %>
				</strong>
				<% if !s.comp_time.nil? %>
					(<%= s.comp_time.to_formatted_s(:h_m)%>)<br />
				<% else %>
					( &#63; )
				<% end %>
			</div>
			<div class="col-xs-8 hidden-sm hidden-md hidden-lg pull-left hidden-print">
				<strong>
					<% if !s.start_time.nil?%>
						<%= s.start_time.to_formatted_s(:d_m_y_h_m)%>
					<% else %>
						( &#63; )
					<% end %>
					&mdash;
					<% if !s.comp_time.nil?%>
						<%= s.comp_time.to_formatted_s(:d_m_y_h_m)%>
					<% else %>
						( &#63; )
					<% end %>
				</strong>
			</div>
			<div class="col-xs-1 hidden-sm hidden-md hidden-lg pull-left hidden-print">
				<% if user_signed_in? %>
				<!-- Button trigger modal -->
					<%= link_to 'send', message_path(:shipment => @shipment.id), {:remote => true,'class' => "btn btn-primary btn-sm",'type' => "button", 'data-toggle' => "modal", 'data-target' => "#messageModal", 'data-recipient' => "@mdo", 'data-subject' => @shipment.vessel.vsl_name} %>
				<% end %>
			</div>
			<div class="col-xs-1 hidden-sm hidden-md hidden-lg pull-right hidden-print">
				<% if user_signed_in? %>
					<%= link_to '<i class="glyphicon glyphicon-remove"></i>'.html_safe, s, :class => 'delete', method: :delete, :remote => true %>
				<% end %>
			</div>
			<div class="col-xs-10 col-sm-7 col-md-8 col-lg-7 pull-left">
				<%= link_to s.status, edit_shipment_status_path(s) %><br />
				<%= s.description %>
			</div>
			<div class="col-xs-1 col-sm-1 col-md-1 col-lg-1 pull-left hidden-xs">
				<% if user_signed_in? %>
					<%= link_to 'send', message_path(:shipment => @shipment.id), {:remote => true, 'class' => "btn btn-primary btn-xs",'type' => "button", 'data-toggle' => "modal", 'data-target' => "#messageModal", 'data-recipient' => "@mdo", 'data-subject' => @shipment.vessel.vsl_name} %>
				<% end %>
			</div>

			<div class="col-xs-1 pull-left hidden-print hidden-xs">
				<% if user_signed_in? %>
					<%= link_to '<i class="glyphicon glyphicon-remove"></i>'.html_safe, s, :class => 'delete', method: :delete, :remote => true %>
				<% end %>
			</div>
		</h5>
	</div>

<% end %>
<br />
<br />
<% if user_signed_in? %>
	<div class="row hidden-print form-group col-xs-12">
		<div class="col-sm-3 col-md-2 col-lg-2" style="padding-left:0px;">
			<button type="button" class="btn btn-danger" data-toggle="collapse" data-target="#add_new_status" aria-expanded="false" aria-controls="add_new_status">
			  New status
			</button>
		</div>
		<br / class="hidden-sm hidden-md hidden-lg">
		<%= form_for(:shipment_status, :url => create_shipment_status_shipment_path()) do |f| %>
			<div id="add_new_status" class="collapse hidden-print col-xs-12 col-sm-9 col-md-10 col-lg-10 hidden-print" style="padding-left:0px;">
				<div class="field col-xs-12 col-sm-6 col-md-5 col-lg-5 hidden-print" style="padding-left:0px;">
					<%= f.text_field :status, :class => "form-control", :id => "inputStatus", :placeholder => "Write short status" %>
					<br / class="hidden-sm hidden-md hidden-lg">
				</div>
				<div class="field col-xs-12 col-sm-6 col-md-5 col-lg-5 hidden-print" style="padding-left:0px;">
					<%= f.text_area :description, :class => "form-control", :id => "inputDescription", :placeholder => "Include more details" %>
					<br />
				</div>
				<div class="field col-xs-12 col-sm-10 col-md-10 col-lg-10 hidden-print" style="padding-left:0px;">
					Start date - time
					<br />
						<%= f.datetime_select :start_time, :order => [:day, :month, :year, :hour, :minute, :second], :use_two_digit_numbers => true, :use_month_numbers => true, :date_separator => " / ", :discard_second => true, :include_blank => true, :default => Date.today, :start_year => 2011, :end_year => Date.today.year + 1, :minute_step => 15, :class => "form-control", :id => "inputStartTime" %>
					<br />
					<br />
				</div>
				<div class="field col-xs-12 col-sm-10 col-md-10 col-lg-10 hidden-print" style="padding-left:0px;">
					Expected completion date - time
					<br />
						<%= f.datetime_select :comp_time, :order => [:day, :month, :year, :hour, :minute, :second], :use_two_digit_numbers => true, :use_month_numbers => true, :date_separator => " / ", :discard_second => true, :include_blank => true, :default => Date.today, :start_year => 2011, :end_year => Date.today.year + 1, :minute_step => 15, :class => "form-control", :id => "inputCompTime" %>
				</div>

				<div class="actions field col-xs-12 col-sm-12 col-md-12 col-lg-12 hidden-print" style="padding-left:0px;">
					<br />
					<%= f.submit "Create", :class => "btn btn-primary" %>&nbsp;&nbsp;&nbsp;
					<a href="#" data-toggle="collapse" data-target="#add_new_status" aria-expanded="false" aria-controls="add_new_status">Cancel</a>
				</div>
			</div>
		<% end %>
	</div>
<% end %>
<br / class="hidden-xs">
<br / class="hidden-xs">
<br / class="hidden-xs">
<br />
<div class="row hidden-print">
	<div class="col-xs-2">
		<%= link_to shipments_path, :type => "button", :class => "btn btn-default btn-xs"  do %>
			<i class="glyphicon glyphicon-arrow-left"></i> Back to list
		<% end %>
	</div>
</div>
<br />