config/routes.rb
Rails.application.routes.draw do

  resources :owners

  resources :shipment_statuses

  get "shipments/message" => 'shipments#message', :as => :message
  
  resources :shipments do
    member do
      post 'create_shipment_status'
    end
  end

  devise_for :users, :path_names => {sign_in: "login", sign_out: "logout"} do
    get 'signup' => 'devise/registrations#new', :as => :new_user_registration
    post 'signup' => 'devise/registrations#create', :as => :user_registration
    get 'users/cancel' => 'devise/registrations#cancel', :as => :cancel_user_registration
    get 'users/edit' => 'devise/registrations#edit', :as => :edit_user_registration
    put 'users' => 'devise/registrations#update'
    delete 'users/cancel' => 'devise/registrations#destroy'  
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'users/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  get 'dash', to: 'vessels#dash', :as => :dash
  get 'non_russian', to: 'vessels#non_russian', :as => :non_russian

  resources :positions
  resources :vessels do
    collection do
      get :dash
      get :maps
      get :non_russian
      get :scan
      get :scan_gps
      post :engage
    end
  end

  get 'about', to: 'static_pages#about'
  
  

  root to: 'vessels#dash'

end

app/views/layouts/_footer.html.erb
<div class="footer navbar-fixed-bottom hidden-print">
	<div class="container">
		<ul class="nav">
			<li><%= link_to "About", about_path %></li>
    	</ul>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar-xs hidden-print">
   <div class="navbar-primary hidden-print">
    <div class="navbar navbar-fixed-top hidden-print" role="navigation">
      <div class="container-fluid hidden-print">
        <div class="navbar-header hidden-print">
          <button class="navbar-toggle collapsed" data-target=".navbar-collapse" data-toggle="collapse" type="button">
            <span class="sr-only hidden-print">Toggle navigation</span>
            <span class="icon-bar hidden-print"></span>
            <span class="icon-bar hidden-print"></span>
            <span class="icon-bar hidden-print"></span>
          </button>
          <%= link_to "Shepherd", root_path, id: "logo", class: "navbar-brand hidden-print" %>
        </div>
        <div class="collapse navbar-collapse hidden-print" id="navbar-collapse">
          <ul class="nav navbar-nav navbar-right hidden-print">
            <li class="<%= "active" if current_page?(dash_path) %> hidden-print"><%= link_to "Dashboard", dash_path %></li>
            <li class="<%= "active" if current_page?(owners_path) %> hidden-print"><%= link_to "Owners", owners_path %></li>
            <li class="<%= "active" if current_page?(shipments_path) %> hidden-print"><%= link_to "Shipments", shipments_path %></li>
            <li class="<%= "active" if current_page?(vessels_path) %>"><%= link_to "Russian", vessels_path %></li>
            <li class="<%= "active" if current_page?(non_russian_path) %>"><%= link_to "Non-russian", non_russian_path %></li>
            
            <% if user_signed_in? %>
              <li class="<%= "active" if current_page?('login_path') %> hidden-print"><%= link_to (current_user.email), edit_user_registration_path %></li>
              <li class="<%= "active" if current_page?('logout_path') %> hidden-print"><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li class="<%= "active" if current_page?('login_path') %> hidden-print"><%= link_to "Log in", new_user_session_path %></li>
            <% end %>
          </ul>
          <!--<form class="navbar-form navbar-right">
            <input class="form-control" type="text" placeholder="Search...">
          </form>-->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissable fade in hidden-print" id="flash">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head class="hidden-print">
  	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= yield(:title)||"Shepherd" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Shepherd" %>">
    <%= stylesheet_link_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js',  'jquery_ujs', 'jasny-bootstrap','jquery.turbolinks','bootstrap', 'bootbox','bootstrap-sprockets','rails.validations.custom', 'rails.validations','flash', 'application', 'data-turbolinks-track' => true %>
    <style id="holderjs-style" type="text/css"></style>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
      <%= render 'layouts/header' %>
        <div class="container">
          <%= render 'layouts/messages' %>
          <%= yield %>
        </div>
  </body>
</html>